"""Safe Git worktree lifecycle for write-capable agent tasks.

The worktree module is intentionally independent from the MCP bridge.  It
accepts only a broker-approved repository root and a server-generated task ID;
Git arguments are assembled internally and always run without a shell.  The
main working tree is never reset, cleaned, or overwritten.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .errors import PolicyError
from .filesystem import redact_text
from .runner import TRUSTED_BIN_DIRS, FixedRunner


MAX_BASE_REF_BYTES = 200
MAX_CHANGED_FILES = 500
_BASE_REF_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/@-]{0,199}$")
_COMMIT_RE = re.compile(r"^[0-9a-f]{40,64}$")


@dataclass(frozen=True, slots=True)
class RepositoryState:
    """The clean/dirty state observed before a worktree is created."""

    repository_root: Path
    head_commit: str
    dirty: bool
    status: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "repository_root": str(self.repository_root),
            "head_commit": self.head_commit,
            "dirty": self.dirty,
            "status": self.status,
        }


@dataclass(frozen=True, slots=True)
class WorktreeInfo:
    """Immutable metadata for one server-owned isolated worktree."""

    path: Path
    repository_root: Path
    base_ref: str
    base_commit: str
    source_dirty: bool
    source_head_commit: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "path": str(self.path),
            "repository_root": str(self.repository_root),
            "base_ref": self.base_ref,
            "base_commit": self.base_commit,
            "source_dirty": self.source_dirty,
            "source_head_commit": self.source_head_commit,
            "cleanup": "explicit_only",
        }


class WorktreeManager:
    """Create and inspect isolated Git worktrees using fixed operations."""

    def __init__(self, data_dir: Path | str):
        root = Path(data_dir).expanduser().absolute()
        if root.is_symlink():
            raise PolicyError("WORKTREE_CONFIG_INVALID", "worktree data directory cannot be a symlink")
        try:
            root.mkdir(parents=True, exist_ok=True)
            root = root.resolve(strict=True)
        except (OSError, RuntimeError) as exc:
            raise PolicyError("WORKTREE_CONFIG_INVALID", "worktree data directory could not be prepared") from exc
        if not root.is_dir():
            raise PolicyError("WORKTREE_CONFIG_INVALID", "worktree data directory must be a directory")
        os.chmod(root, 0o700)
        self.root = root
        self.worktree_root = root / "agent-worktrees"
        self.worktree_root.mkdir(parents=True, exist_ok=True)
        os.chmod(self.worktree_root, 0o700)

    def inspect_repository(self, scope_root: Path | str) -> RepositoryState:
        """Return repository identity and dirty state without mutating it."""

        requested = self._canonical_directory(scope_root, "scope root")
        repository_root = self._git_root(requested)
        if repository_root != requested:
            raise PolicyError(
                "WORKTREE_SCOPE_INVALID",
                "write-capable agent scope must be the Git repository root, not a subdirectory",
            )
        head = self._git(repository_root, ["rev-parse", "--verify", "HEAD"], timeout_seconds=30)
        if head.returncode != 0:
            raise PolicyError("BASE_COMMIT_UNAVAILABLE", "the approved project has no resolvable HEAD commit")
        head_commit = self._single_line(head.stdout)
        if not _COMMIT_RE.fullmatch(head_commit):
            raise PolicyError("BASE_COMMIT_INVALID", "Git returned an invalid HEAD commit")
        status = self._git(
            repository_root,
            ["status", "--short", "--branch", "--untracked-files=all"],
            timeout_seconds=30,
        )
        if status.returncode != 0:
            raise PolicyError("GIT_STATUS_FAILED", "unable to inspect the approved project working tree")
        status_text = redact_text(status.stdout)[:32_768]
        dirty = any(
            line and not line.startswith("##") and line.strip()
            for line in status_text.splitlines()
        )
        return RepositoryState(repository_root, head_commit, dirty, status_text)

    def prepare(
        self,
        scope_root: Path | str,
        task_id: str,
        *,
        base_ref: str | None = None,
    ) -> WorktreeInfo:
        """Create one detached worktree at a validated commit.

        The task ID is generated by the runtime, so callers cannot choose a
        filesystem path.  A collision fails closed and never overwrites an
        existing directory.
        """

        state = self.inspect_repository(scope_root)
        requested_ref = self.validate_base_ref(base_ref or "HEAD")
        resolved = self._git(
            state.repository_root,
            ["rev-parse", "--verify", "--end-of-options", f"{requested_ref}^{{commit}}"],
            timeout_seconds=30,
        )
        if resolved.returncode != 0:
            raise PolicyError("BASE_REF_INVALID", "base_ref does not resolve to a commit in the approved repository")
        base_commit = self._single_line(resolved.stdout)
        if not _COMMIT_RE.fullmatch(base_commit):
            raise PolicyError("BASE_COMMIT_INVALID", "Git returned an invalid base commit")

        if not isinstance(task_id, str) or not re.fullmatch(r"[0-9a-f]{8,64}", task_id):
            raise PolicyError("WORKTREE_TASK_ID_INVALID", "worktree task identity is invalid")
        target = self.worktree_root / task_id
        try:
            target.relative_to(state.repository_root)
        except ValueError:
            pass
        else:
            raise PolicyError("WORKTREE_CONFIG_INVALID", "worktree storage must be outside the approved repository")
        if target.exists() or target.is_symlink():
            raise PolicyError("WORKTREE_COLLISION", "the generated worktree path already exists")

        created = self._git(
            state.repository_root,
            ["worktree", "add", "--detach", str(target), base_commit],
            timeout_seconds=120,
        )
        if created.returncode != 0:
            message = redact_text(created.stderr or created.stdout)[:2_000]
            raise PolicyError(
                "WORKTREE_CREATE_FAILED",
                "unable to create an isolated worktree" + (f": {message}" if message else ""),
            )
        try:
            canonical_target = self._canonical_directory(target, "created worktree")
        except PolicyError:
            # Only remove a path that this manager just created and only via
            # Git's non-force worktree operation.  No broad filesystem cleanup
            # is attempted.
            self._safe_remove_broken_worktree(target)
            raise
        return WorktreeInfo(
            path=canonical_target,
            repository_root=state.repository_root,
            base_ref=requested_ref,
            base_commit=base_commit,
            source_dirty=state.dirty,
            source_head_commit=state.head_commit,
        )

    def read_head(self, scope_root: Path | str) -> str | None:
        """Return a repository HEAD for read-only task metadata when available."""

        requested = self._canonical_directory(scope_root, "scope root")
        try:
            repository_root = self._git_root(requested)
        except PolicyError as exc:
            if exc.code == "WORKTREE_REQUIRED":
                return None
            raise
        result = self._git(repository_root, ["rev-parse", "--verify", "HEAD"], timeout_seconds=30)
        if result.returncode != 0:
            return None
        head = self._single_line(result.stdout)
        if not _COMMIT_RE.fullmatch(head):
            return None
        return head

    def validate_owned_worktree(self, worktree: Path | str) -> Path:
        """Resolve one existing worktree and prove it belongs to this manager."""

        canonical = self._canonical_directory(worktree, "worktree")
        try:
            relative = canonical.relative_to(self.worktree_root)
        except ValueError as exc:
            raise PolicyError("WORKTREE_NOT_OWNED", "worktree is outside the agent worktree directory") from exc
        if len(relative.parts) != 1 or not re.fullmatch(r"[0-9a-f]{8,64}", relative.parts[0]):
            raise PolicyError("WORKTREE_NOT_OWNED", "worktree identity is not manager-generated")
        return canonical

    def changed_files(self, worktree: Path | str) -> list[str]:
        """Return bounded relative paths reported by Git status."""

        root = self._canonical_directory(worktree, "worktree")
        result = self._git(root, ["status", "--porcelain=v1", "--untracked-files=all"], timeout_seconds=30)
        if result.returncode != 0:
            raise PolicyError("GIT_STATUS_FAILED", "unable to inspect the agent worktree")
        paths: list[str] = []
        for line in result.stdout.splitlines():
            if len(line) < 4 or line[:2] == "!!":
                continue
            raw = line[3:].strip()
            if " -> " in raw:
                raw = raw.rsplit(" -> ", 1)[-1].strip()
            raw = raw.strip('"')
            if not raw or raw.startswith("/") or ".." in Path(raw).parts:
                continue
            if raw not in paths:
                paths.append(raw)
            if len(paths) >= MAX_CHANGED_FILES:
                break
        return paths

    def explicit_cleanup(self, worktree: Path | str) -> None:
        """Remove one owned worktree only when an explicit caller requests it."""

        root = self.validate_owned_worktree(worktree)
        result = self._git(root, ["worktree", "remove", str(root)], timeout_seconds=120)
        if result.returncode != 0:
            raise PolicyError("WORKTREE_CLEANUP_FAILED", "worktree cleanup was not completed; evidence was preserved")

    @staticmethod
    def validate_base_ref(value: str) -> str:
        if not isinstance(value, str) or not value or len(value.encode("utf-8", errors="ignore")) > MAX_BASE_REF_BYTES:
            raise PolicyError("BASE_REF_INVALID", "base_ref must be a bounded Git ref")
        if "\x00" in value or _BASE_REF_RE.fullmatch(value) is None:
            raise PolicyError("BASE_REF_INVALID", "base_ref contains unsupported Git syntax")
        if value.startswith("-") or value.endswith("/") or value.endswith("."):
            raise PolicyError("BASE_REF_INVALID", "base_ref contains unsupported Git syntax")
        if ".." in value or "@{" in value or "/." in value:
            raise PolicyError("BASE_REF_INVALID", "base_ref contains unsupported Git syntax")
        return value

    @staticmethod
    def _canonical_directory(value: Path | str, label: str) -> Path:
        try:
            path = Path(value)
        except (TypeError, ValueError) as exc:
            raise PolicyError("WORKTREE_PATH_INVALID", f"{label} must be an absolute directory") from exc
        if not path.is_absolute() or path.is_symlink():
            raise PolicyError("WORKTREE_PATH_INVALID", f"{label} must be an absolute non-symlink directory")
        try:
            resolved = path.resolve(strict=True)
        except (OSError, RuntimeError, FileNotFoundError) as exc:
            raise PolicyError("WORKTREE_PATH_INVALID", f"{label} could not be resolved") from exc
        if not resolved.is_dir():
            raise PolicyError("WORKTREE_PATH_INVALID", f"{label} must be a directory")
        return resolved

    def _git_root(self, path: Path) -> Path:
        result = self._git(path, ["rev-parse", "--show-toplevel"], timeout_seconds=30)
        if result.returncode != 0:
            raise PolicyError("WORKTREE_REQUIRED", "write-capable agent tasks require an approved Git repository")
        try:
            root = Path(self._single_line(result.stdout)).resolve(strict=True)
        except (OSError, RuntimeError, ValueError) as exc:
            raise PolicyError("WORKTREE_REQUIRED", "Git repository root could not be resolved") from exc
        if not root.is_dir() or root.is_symlink():
            raise PolicyError("WORKTREE_REQUIRED", "Git repository root is not a regular directory")
        return root

    @staticmethod
    def _single_line(value: str) -> str:
        return next((line.strip() for line in value.splitlines() if line.strip()), "")

    def _git(self, cwd: Path, args: list[str], *, timeout_seconds: int) -> subprocess.CompletedProcess[str]:
        if any(not isinstance(item, str) or not item or "\x00" in item for item in args):
            raise PolicyError("GIT_OPERATION_NOT_ALLOWED", "internal Git arguments are invalid")
        argv = FixedRunner._git(["-c", "core.hooksPath=/dev/null", *args])
        environment = {
            "PATH": os.pathsep.join(str(path) for path in TRUSTED_BIN_DIRS),
            "HOME": str(self.root / "runtime-home"),
            "TMPDIR": str(self.root / "runtime-tmp"),
            "LANG": "C.UTF-8",
            "LC_ALL": "C.UTF-8",
            "CI": "1",
            "GIT_CONFIG_GLOBAL": os.devnull,
            "GIT_CONFIG_SYSTEM": os.devnull,
            "GIT_TERMINAL_PROMPT": "0",
            "PAGER": "cat",
            "NO_COLOR": "1",
        }
        (self.root / "runtime-home").mkdir(exist_ok=True)
        (self.root / "runtime-tmp").mkdir(exist_ok=True)
        try:
            return subprocess.run(
                argv,
                cwd=cwd,
                env=environment,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=timeout_seconds,
                check=False,
                shell=False,
                text=True,
                start_new_session=True,
            )
        except subprocess.TimeoutExpired as exc:
            raise PolicyError("GIT_TIMEOUT", "the fixed Git operation exceeded its timeout") from exc
        except OSError as exc:
            raise PolicyError("GIT_UNAVAILABLE", "unable to start the fixed Git adapter") from exc

    def _safe_remove_broken_worktree(self, path: Path) -> None:
        try:
            path.relative_to(self.worktree_root)
        except ValueError:
            return
        try:
            if path.is_dir() and not path.is_symlink():
                shutil.rmtree(path)
        except OSError:
            return


__all__ = ["RepositoryState", "WorktreeInfo", "WorktreeManager"]
